# Generated by Django 5.2.1 on 2025-06-05 06:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_status_task_alter_emailtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField(help_text='Одна почта получателя')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailTask',
        ),
    ]
