# Generated by Django 5.2.1 on 2025-06-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_name_task_body_task_created_at_and_more'),
    ]

    operations = [
    ]
