# Generated by Django 5.2.1 on 2025-06-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_email_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='namewe',
        ),
    ]
