# Generated by Django 5.2.1 on 2025-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_status_namewe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='namewe',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
