# Generated by Django 5.2.1 on 2025-06-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_namewe_status_name_alter_task_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.CharField(default='kek', max_length=200),
            preserve_default=False,
        ),
    ]
