# Generated by Django 5.2.1 on 2025-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_status_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='subject',
            new_name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='recipient_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
