# Generated by Django 5.2.1 on 2025-06-05 08:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_email_status_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 8, 27, 1, 56665)),
        ),
    ]
