# Generated by Django 5.2.1 on 2025-06-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_email_bafag_alter_task_created_at'),
    ]

    operations = [

    ]
