# Generated by Django 5.2.1 on 2025-06-05 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_task_created_at'),
    ]

    operations = [

    ]
