# Generated by Django 5.2.1 on 2025-06-05 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status'),
        )
    ]
