# Generated by Django 5.2.1 on 2025-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recipient_list',
        ),
        migrations.AddField(
            model_name='email',
            name='recipient_list',
            field=models.TextField(default=' ', help_text='Введите почты получателей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('tasks', models.ManyToManyField(related_name='recipients', to='app.email')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
    ]
