# Generated by Django 5.2.1 on 2025-06-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_email_recipient_remove_task_recipient_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='email',
            name='recipient_list',
        ),
        migrations.AddField(
            model_name='email',
            name='recipient_list',
            field=models.ManyToManyField(related_name='recipients', to='app.recipient'),
        ),
    ]
